# Generated by Django 6.0.3 on 2026-04-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
