# Generated by Django 6.0.4 on 2026-05-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0002_dailyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadHuerfana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_crudo', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AliasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(help_text='Nombre tal como viene de la fuente externa', max_length=200, unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='predicciones.equipos')),
            ],
        ),
    ]
