# Generated by Django 6.0.4 on 2026-05-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0003_entidadhuerfana_aliasequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='liga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
