# Generated by Django 6.0.4 on 2026-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0004_equipos_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
