# Generated by Django 6.0.4 on 2026-05-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0005_equipos_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='logo_url',
        ),
    ]
