# Generated by Django 6.0.4 on 2026-05-19 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0006_remove_equipos_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='away_team_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_away', to='predicciones.equipos'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='home_team_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_home', to='predicciones.equipos'),
        ),
        migrations.CreateModel(
            name='FBrefPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbref_player_stats', to='predicciones.equipos')),
            ],
            options={
                'verbose_name': 'FBref Player Stats',
            },
        ),
        migrations.CreateModel(
            name='FBrefShootingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('goles', models.IntegerField(blank=True, default=0, null=True)),
                ('tiros', models.IntegerField(blank=True, default=0, null=True)),
                ('tiros_puerta', models.IntegerField(blank=True, default=0, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbref_shooting_stats', to='predicciones.equipos')),
            ],
            options={
                'verbose_name': 'FBref Shooting Stats',
            },
        ),
        migrations.CreateModel(
            name='FBrefTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbref_team_stats', to='predicciones.equipos')),
            ],
            options={
                'verbose_name': 'FBref Team Stats',
            },
        ),
    ]
