# Generated by Django 6.0.4 on 2026-05-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0007_dailyschedule_away_team_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqlalchemy_equipo_id', models.IntegerField(help_text='ID del equipo en la tabla SQLAlchemy equipos.id_equipo', unique=True)),
                ('sqlalchemy_equipo_nombre', models.CharField(help_text='Nombre del equipo en SQLAlchemy (denormalizado)', max_length=100)),
                ('confianza', models.FloatField(default=0.0, help_text='Score del fuzzy match que generó el mapping (0-100)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('django_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='predicciones.equipos')),
            ],
            options={
                'verbose_name': 'Mapping Django ↔ SQLAlchemy',
                'verbose_name_plural': 'Mappings Django ↔ SQLAlchemy',
            },
        ),
    ]
