# Generated by Django 6.0.4 on 2026-05-19 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0008_equipomapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipomapping',
            options={'verbose_name': 'Mapping Django <-> SQLAlchemy', 'verbose_name_plural': 'Mappings Django <-> SQLAlchemy'},
        ),
    ]
