# Generated by Django 6.0.4 on 2026-05-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0009_alter_equipomapping_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbrefplayerstats',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='fbrefshootingstats',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='fbrefteamstats',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='away_team_fk',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='home_team_fk',
        ),
        migrations.DeleteModel(
            name='EquipoMapping',
        ),
        migrations.DeleteModel(
            name='FBrefPlayerStats',
        ),
        migrations.DeleteModel(
            name='FBrefShootingStats',
        ),
        migrations.DeleteModel(
            name='FBrefTeamStats',
        ),
    ]
