# Generated by Django 6.0.x on 2026-05-20
# Migracion para esquema normalizado v2.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0010_remove_fbrefplayerstats_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='id_equipo',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_partido',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='fstatus',
            field=models.CharField(blank=True, default='Fixture', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='jugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='predicciones.equipos', db_column='id_local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='predicciones.equipos', db_column='id_visitante'),
        ),
        migrations.AlterUniqueTogether(
            name='partido',
            unique_together={('local', 'visitante', 'fecha')},
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_local', to='predicciones.equipos', db_column='equipo_local_fk'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_visitante', to='predicciones.equipos', db_column='equipo_visitante_fk'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('sport', 'home_team', 'away_team', 'match_date')},
        ),
    ]
